version: '3.3'
services:
  app:
    container_name: gurukul-app
    restart: always
    build: .
    depends_on:
        - mongodb
    ports:
      - '80:3000'
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'